# Generated by Django 2.2.4 on 2019-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='用户唯一 ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='wx_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信 ID'),
        ),
    ]
