# Generated by Django 2.2.4 on 2019-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190829_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(max_length=64, unique=True, verbose_name='用户唯一 ID'),
        ),
    ]
